# Generated by Django 4.2 on 2023-04-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honeypot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattemptextended",
            name="ip_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ip address"
            ),
        ),
    ]
