# Generated by Django 4.2 on 2023-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_honeypot", "0002_auto_20160208_0854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="ip_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ip address"
            ),
        ),
    ]
